# Generated by Django 4.2.7 on 2023-11-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='Item',
        ),
    ]
