# Generated by Django 4.2.7 on 2023-11-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_menu', '0002_rename_listitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
