# Generated by Django 4.2.7 on 2023-11-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_menu', '0004_menu_remove_item_menu_item_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display_menu.menu'),
        ),
    ]
